fras/apps/home/urls.py
from django.urls import path
from apps.home import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'user'

urlpatterns = [

    # The home page
    path('', views.index, name='user_home'),
    path('user_register/', views.user_register, name='user_register'),
    path('create_one/', views.create_one, name='create_one'),
    path('user_register_attendance/<int:id>/', views.user_register_attendance, name='user_register_attendance'),
    path('camera_feed/',views.camera_feed, name='camera_feed'),
    path('get_id/',views.get_id, name='get_id'),
    path('train_data/',views.train_data, name='train_data'),
    path('In_cam/',views.In_cam, name='In_cam'),
    path('Out_cam/',views.Out_cam, name='Out_cam'),
    path('report/',views.report, name='report'),
    path('User_report/<int:id>/',views.User_report, name='User_report'),
    path('calender/', views.calender, name='calender'),
    path('IN_Temp/',views.IN_Temp, name='IN_Temp'),
    path('Out_Temp/',views.Out_Temp, name='Out_Temp'),
    path('attendance_report/',views.attendance_report, name='attendance_report'),
    path('get_attendance_events/', views.get_attendance_events, name='get_attendance_events'),
    path('api/employees', views.fetch_employees, name='fetch_employees'),
    path('api/attendance/', views.attendance_view, name='attendance_view'),
    path('api/employee-details', views.check_employee_presence, name='employee_details'),
    path('api/eventdata', views.calender_event_data, name='eventdata'),
    path('unknow_view',views.unknown_view, name='unknow_view'),
    path('daily_attendance_page/',views.daily_attendance_page, name='daily_attendance_page'),
    path('api/check_daily_employee_presence', views.check_daily_employee_presence, name='check_daily_employee_presence'),
    path('accept_unknown/<int:id>/', views.accept_unknown, name='accept_unknown'),
    path('reject_unknown/<int:id>/', views.reject_unknown, name='reject_unknown'),
    path('api/fetch_daily_employees', views.fetch_daily_employees, name='fetch_daily_employees'),
    path('api/daily_employee_attendance/', views.daily_employee_attendance, name='daily_employee_attendance'),
    path('show_rejected', views.show_rejected, name='show_rejected'),
    path('delete_rejected/<int:id>/', views.delete_rejected, name='delete_rejected'),
    path('delete_selected_unknowns/', views.delete_selected_unknowns, name='delete_selected_unknowns'),
    path('delete_selected_rejects/', views.delete_selected_rejects, name='delete_selected_rejects'),
    path('generate_report/',views.generate_report, name='generate_report'),
    # path('chart/attendance/', views.daily_attendance_view, name='attendance_view'),
    
 ]

urlpatterns += staticfiles_urlpatterns()

    

fras/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))             # UI Kits Html files
]

fras/apps/templates/includes/footer-fullscreen.html
<!--    <footer class="py-5">-->
<!--      <div class="container">-->
<!--        <div class="row align-items-center justify-content-xl-between">-->
<!--          <div class="col-xl-6">-->
<!--            <div class="copyright text-center text-xl-left text-muted">-->
<!--                <a target="_blank" -->
<!--                   href="https://appseed.us/admin-dashboards/django" -->
<!--                   class="font-weight-bold ml-1" target="_blank">More Dashboards</a>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="col-xl-6">-->
<!--            <div class="text-center text-xl-right text-muted">-->
<!--               &copy; <a target="_blank" -->
<!--                         href="https://bit.ly/3fKQZaL">Creative-Tim</a> -->
<!--               - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </footer>-->

fras/apps/templates/includes/footer.html
<!--      &lt;!&ndash; Footer &ndash;&gt;-->
<!--      <footer class="footer">-->
<!--        <div class="row align-items-center justify-content-xl-between">-->
<!--          <div class="col-xl-6">-->
<!--            <div class="text-center text-xl-left text-muted">-->
<!--              <a href="https://appseed.us/admin-dashboards/django" -->
<!--                 class="font-weight-bold ml-1" target="_blank">More Dashboards</a>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="col-xl-6">-->
<!--            <div class="text-center text-xl-right text-muted">-->
<!--              <a href="https://bit.ly/3fKQZaL" -->
<!--                 class="font-weight-bold ml-1" target="_blank"> &copy; Creative-Tim</a> -->
<!--                 - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </footer>-->

fras/apps/templates/includes/navigation-fullscreen.html
<!--<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">-->
<!--  <div class="container">-->
<!--    <a class="navbar-brand" href="/">-->
<!--      <img src="/static/assets/img/brand/white.png" alt="Argon Design - Template Starter Logo.">-->
<!--    </a>-->
<!--    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">-->
<!--      <div class="navbar-collapse-header">-->
<!--        <div class="row">-->
<!--          <div class="col-6 collapse-brand">-->
<!--            <a href="/">-->
<!--              <img src="/static/assets/img/brand/blue.png">-->
<!--            </a>-->
<!--          </div>-->
<!--          <div class="col-6 collapse-close">-->
<!--            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">-->
<!--              <span></span>-->
<!--              <span></span>-->
<!--            </button>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--      <ul class="navbar-nav mr-auto">-->
<!--        <li class="nav-item">-->
<!--          <a href="{% url 'login' %}" class="nav-link">-->
<!--            <span class="nav-link-inner&#45;&#45;text">Login</span>-->
<!--          </a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a href="{% url 'register' %}" class="nav-link">-->
<!--            <span class="nav-link-inner&#45;&#45;text">Register</span>-->
<!--          </a>-->
<!--        </li>-->
<!--      </ul>-->
<!--      <hr class="d-lg-none" />-->
<!--      <ul class="navbar-nav align-items-lg-center ml-lg-auto">-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link nav-link-icon" href="https://www.facebook.com/webappseed" -->
<!--             target="_blank" data-toggle="tooltip" data-original-title="Like us on Facebook">-->
<!--            <i class="fab fa-facebook-square"></i>-->
<!--            <span class="nav-link-inner&#45;&#45;text d-lg-none">Facebook</span>-->
<!--          </a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link nav-link-icon" href="https://twitter.com/webappseed" -->
<!--             target="_blank" data-toggle="tooltip" data-original-title="Follow us on Twitter">-->
<!--            <i class="fab fa-twitter-square"></i>-->
<!--            <span class="nav-link-inner&#45;&#45;text d-lg-none">Twitter</span>-->
<!--          </a>-->
<!--        </li>-->
<!--        <li class="nav-item d-none d-lg-block ml-lg-4">-->
<!--          <a href="https://appseed.us/admin-dashboards/django-dashboard-argon-pro" -->
<!--             target="_blank" class="btn btn-neutral btn-icon">-->
<!--            <span class="btn-inner&#45;&#45;icon">-->
<!--              <i class="fas fa-rocket mr-2"></i>-->
<!--            </span>-->
<!--            <span class="nav-link-inner&#45;&#45;text">PRO Version</span>-->
<!--          </a>-->
<!--        </li>-->
<!--      </ul>-->
<!--    </div>-->
<!--  </div>-->
<!--</nav>-->

fras/apps/templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--            <i class="ni ni-bell-55"></i>-->
<!--          </a>-->
<!--          <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">-->
            <!-- Dropdown header -->
<!--            <div class="px-3 py-3">-->
<!--              <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">13</strong> notifications.</h6>-->
<!--            </div>-->
<!--            &lt;!&ndash; List group &ndash;&gt;-->
<!--            <div class="list-group list-group-flush">-->
<!--              <a href="#!" class="list-group-item list-group-item-action">-->
<!--                <div class="row align-items-center">-->
<!--                  <div class="col-auto">-->
<!--                    &lt;!&ndash; Avatar &ndash;&gt;-->
<!--                    <img alt="Image placeholder" src="/static/assets/img/theme/team-1.jpg" class="avatar rounded-circle">-->
<!--                  </div>-->
<!--                  <div class="col ml&#45;&#45;2">-->
<!--                    <div class="d-flex justify-content-between align-items-center">-->
<!--                      <div>-->
<!--                        <h4 class="mb-0 text-sm">John Snow</h4>-->
<!--                      </div>-->
<!--                      <div class="text-right text-muted">-->
<!--                        <small>2 hrs ago</small>-->
<!--                      </div>-->
<!--                    </div>-->
<!--                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="#!" class="list-group-item list-group-item-action">-->
<!--                <div class="row align-items-center">-->
<!--                  <div class="col-auto">-->
<!--                    &lt;!&ndash; Avatar &ndash;&gt;-->
<!--                    <img alt="Image placeholder" src="/static/assets/img/theme/team-2.jpg" class="avatar rounded-circle">-->
<!--                  </div>-->
<!--                  <div class="col ml&#45;&#45;2">-->
<!--                    <div class="d-flex justify-content-between align-items-center">-->
<!--                      <div>-->
<!--                        <h4 class="mb-0 text-sm">John Snow</h4>-->
<!--                      </div>-->
<!--                      <div class="text-right text-muted">-->
<!--                        <small>3 hrs ago</small>-->
<!--                      </div>-->
<!--                    </div>-->
<!--                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="#!" class="list-group-item list-group-item-action">-->
<!--                <div class="row align-items-center">-->
<!--                  <div class="col-auto">-->
<!--                    &lt;!&ndash; Avatar &ndash;&gt;-->
<!--                    <img alt="Image placeholder" src="/static/assets/img/theme/team-3.jpg" class="avatar rounded-circle">-->
<!--                  </div>-->
<!--                  <div class="col ml&#45;&#45;2">-->
<!--                    <div class="d-flex justify-content-between align-items-center">-->
<!--                      <div>-->
<!--                        <h4 class="mb-0 text-sm">John Snow</h4>-->
<!--                      </div>-->
<!--                      <div class="text-right text-muted">-->
<!--                        <small>5 hrs ago</small>-->
<!--                      </div>-->
<!--                    </div>-->
<!--                    <p class="text-sm mb-0">Your posts have been liked a lot.</p>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="#!" class="list-group-item list-group-item-action">-->
<!--                <div class="row align-items-center">-->
<!--                  <div class="col-auto">-->
<!--                    &lt;!&ndash; Avatar &ndash;&gt;-->
<!--                    <img alt="Image placeholder" src="/static/assets/img/theme/team-4.jpg" class="avatar rounded-circle">-->
<!--                  </div>-->
<!--                  <div class="col ml&#45;&#45;2">-->
<!--                    <div class="d-flex justify-content-between align-items-center">-->
<!--                      <div>-->
<!--                        <h4 class="mb-0 text-sm">John Snow</h4>-->
<!--                      </div>-->
<!--                      <div class="text-right text-muted">-->
<!--                        <small>2 hrs ago</small>-->
<!--                      </div>-->
<!--                    </div>-->
<!--                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </a>-->
<!--              <a href="#!" class="list-group-item list-group-item-action">-->
<!--                <div class="row align-items-center">-->
<!--                  <div class="col-auto">-->
<!--                    &lt;!&ndash; Avatar &ndash;&gt;-->
<!--                    <img alt="Image placeholder" src="/static/assets/img/theme/team-5.jpg" class="avatar rounded-circle">-->
<!--                  </div>-->
<!--                  <div class="col ml&#45;&#45;2">-->
<!--                    <div class="d-flex justify-content-between align-items-center">-->
<!--                      <div>-->
<!--                        <h4 class="mb-0 text-sm">John Snow</h4>-->
<!--                      </div>-->
<!--                      <div class="text-right text-muted">-->
<!--                        <small>3 hrs ago</small>-->
<!--                      </div>-->
<!--                    </div>-->
<!--                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </a>-->
<!--            </div>-->
<!--            &lt;!&ndash; View all &ndash;&gt;-->
<!--            <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>-->
<!--          </div>-->
<!--        </li>-->
<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--            <i class="ni ni-ungroup"></i>-->
<!--          </a>-->
<!--          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right ">-->
<!--            <div class="row shortcuts px-4">-->
<!--              <a href="#!" class="col-4 shortcut-item">-->
<!--                <span class="shortcut-media avatar rounded-circle bg-gradient-red">-->
<!--                  <i class="ni ni-calendar-grid-58"></i>-->
<!--                </span>-->
<!--                <small>Calendar</small>-->
<!--              </a>-->
<!--              <a href="#!" class="col-4 shortcut-item">-->
<!--                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">-->
<!--                  <i class="ni ni-email-83"></i>-->
<!--                </span>-->
<!--                <small>Email</small>-->
<!--              </a>-->
<!--              <a href="#!" class="col-4 shortcut-item">-->
<!--                <span class="shortcut-media avatar rounded-circle bg-gradient-info">-->
<!--                  <i class="ni ni-credit-card"></i>-->
<!--                </span>-->
<!--                <small>Payments</small>-->
<!--              </a>-->
<!--              <a href="#!" class="col-4 shortcut-item">-->
<!--                <span class="shortcut-media avatar rounded-circle bg-gradient-green">-->
<!--                  <i class="ni ni-books"></i>-->
<!--                </span>-->
<!--                <small>Reports</small>-->
<!--              </a>-->
<!--              <a href="#!" class="col-4 shortcut-item">-->
<!--                <span class="shortcut-media avatar rounded-circle bg-gradient-purple">-->
<!--                  <i class="ni ni-pin-3"></i>-->
<!--                </span>-->
<!--                <small>Maps</small>-->
<!--              </a>-->
<!--              <a href="#!" class="col-4 shortcut-item">-->
<!--                <span class="shortcut-media avatar rounded-circle bg-gradient-yellow">-->
<!--                  <i class="ni ni-basket"></i>-->
<!--                </span>-->
<!--                <small>Shop</small>-->
<!--              </a>-->
<!--            </div>-->
<!--          </div>-->
<!--        </li>-->
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="/static/assets/img/theme/team-4.jpg">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{ request.user.username }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="{% url 'profile' %}" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
<!--            <a target="_blank" href="http://appseed.us/support" class="dropdown-item">-->
<!--              <i class="ni ni-support-16"></i>-->
<!--              <span>Support</span>-->
<!--            </a>-->
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item">
              <i class="ni ni-user-run text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

fras/apps/templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>

fras/apps/templates/includes/sidenav.html
<aside class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url "user:user_home" %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Register</span>
            </a>
          <!-- </li>
           <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url "user:report" %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Reporting</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url "user:user_register" %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Attendance</span>
            </a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url "user:IN_Temp" %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Cam-IN FEED</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url "user:Out_Temp" %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Cam-OUT FEED</span>
            </a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url "user:attendance_report" %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Attendance Report</span>
            </a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url "user:daily_attendance_page" %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Daily Attendance Report</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url "user:unknow_view" %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Anonymous Detections</span>
            </a>
          </li>

          <!-- <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url "user:show_rejected" %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Rejected Detections</span>
            </a>
          </li> -->
        </ul>
      </div>
    </div>
  </div>
</aside>