fras/apps/home/urls.py
from django.urls import path
from apps.home import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'user'

urlpatterns = [

    # The home page
    path('', views.index, name='user_home'),
    path('user_register/', views.user_register, name='user_register'),
    path('create_one/', views.create_one, name='create_one'),
    path('user_register_attendance/<int:id>/', views.user_register_attendance, name='user_register_attendance'),
    path('camera_feed/',views.camera_feed, name='camera_feed'),
    path('get_id/',views.get_id, name='get_id'),
    path('train_data/',views.train_data, name='train_data'),
    path('In_cam/',views.In_cam, name='In_cam'),
    path('Out_cam/',views.Out_cam, name='Out_cam'),
    path('report/',views.report, name='report'),
    path('User_report/<int:id>/',views.User_report, name='User_report'),
    path('calender/', views.calender, name='calender'),
    path('IN_Temp/',views.IN_Temp, name='IN_Temp'),
    path('Out_Temp/',views.Out_Temp, name='Out_Temp'),
    path('attendance_report/',views.attendance_report, name='attendance_report'),
    path('get_attendance_events/', views.get_attendance_events, name='get_attendance_events'),
    path('api/employees', views.fetch_employees, name='fetch_employees'),
    path('api/attendance/', views.attendance_view, name='attendance_view'),
    path('api/employee-details', views.check_employee_presence, name='employee_details'),
    path('api/eventdata', views.calender_event_data, name='eventdata'),
    path('unknow_view',views.unknown_view, name='unknow_view'),
    path('daily_attendance_page/',views.daily_attendance_page, name='daily_attendance_page'),
    path('api/check_daily_employee_presence', views.check_daily_employee_presence, name='check_daily_employee_presence'),
    path('accept_unknown/<int:id>/', views.accept_unknown, name='accept_unknown'),
    path('reject_unknown/<int:id>/', views.reject_unknown, name='reject_unknown'),
    path('api/fetch_daily_employees', views.fetch_daily_employees, name='fetch_daily_employees'),
    path('api/daily_employee_attendance/', views.daily_employee_attendance, name='daily_employee_attendance'),
    path('show_rejected', views.show_rejected, name='show_rejected'),
    path('delete_rejected/<int:id>/', views.delete_rejected, name='delete_rejected'),
    path('delete_selected_unknowns/', views.delete_selected_unknowns, name='delete_selected_unknowns'),
    path('delete_selected_rejects/', views.delete_selected_rejects, name='delete_selected_rejects'),
    path('generate_report/',views.generate_report, name='generate_report'),
    # path('chart/attendance/', views.daily_attendance_view, name='attendance_view'),
    
 ]

urlpatterns += staticfiles_urlpatterns()

    

fras/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))             # UI Kits Html files
]

fras/apps/home/models.py
from django.db import models

class registration(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=191)
    department = models.CharField(max_length=191)
    date_time = models.DateTimeField(auto_now_add=True)
    image = models.BinaryField(null=True)
    class Meta:
        db_table = 'registration'
        
class attendance(models.Model):
    emp_id = models.ForeignKey(registration, on_delete=models.CASCADE)
    status = models.CharField(max_length=191)
    date_time = models.DateTimeField(auto_now=True)
    image = models.BinaryField(null=True)
    class Meta:
        db_table = 'attendance'
               
class unknown(models.Model):
    status = models.CharField(max_length=191)
    date_time = models.DateTimeField(auto_now=True)
    image = models.BinaryField(null=True)
    class Meta:
        db_table = 'unknown'
        
        
        
class rejected_unknown(models.Model):
    status = models.CharField(max_length=191)
    date_time = models.DateTimeField()
    image = models.BinaryField(null=True)
    class Meta:
        db_table = 'rejected_unknown'

fras/apps/home/views.py
from django.contrib.auth.decorators import login_required
from django.http import StreamingHttpResponse
from apps.home.models import *
from datetime import datetime, timedelta ,date
from django.http import HttpResponseNotFound
from django.db.models import Count, Min, Max, Q, Value
from django.db.models.functions import Coalesce
from .models import registration, attendance
from django.views.decorators import gzip
from django.shortcuts import render
from datetime import datetime, timezone
from apps.home.architecture import *
from sklearn.preprocessing import Normalizer
from django.utils import timezone
from django.db.models.functions import TruncMonth
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import mediapipe as mp
import pytz, os, cv2, pyttsx3, time, shutil, base64, json, threading, mtcnn, pickle, decimal
from calendar import monthrange
from django.core.exceptions import ObjectDoesNotExist
import numpy as np
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import tensorflow as tf
import multiprocessing
from keras.models import load_model
from scipy.spatial.distance import cosine
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, redirect
from apps.home.form import AttendanceForm
from django.core.paginator import Paginator, EmptyPage
from pytz import timezone as tz
from ultralytics import YOLO
import cv2
from ultralytics.utils.plotting import Annotator


global dic
dic={
    'id':None,
    'name':None,
    'department':None,
    'img_string':None
}



def load_pickle(path):
    with open(path, 'rb') as f:
        encoding_dict = pickle.load(f)
    return encoding_dict


def normalize(img):
    mean, std = img.mean(), img.std()
    return (img - mean) / std


@login_required(login_url="/login/")
def index(request):
    return render(request,"home/index.html")


@login_required(login_url="/login/")
def user_register(request):
    ignored_id = 1
    employees = registration.objects.all().order_by('-id').exclude(id=ignored_id)

    paginator = Paginator(employees, 10)  # You can adjust the page size as needed
    page_num = request.GET.get('page')

    try:
        paginated_data = paginator.get_page(page_num)
    except EmptyPage:
        # Handle the case where the requested page is out of range
        paginated_data = paginator.get_page(1)

    context = {'data': []}
    for item in paginated_data:
        image_data = item.image  
        image_data_base64 = base64.b64encode(image_data).decode('utf-8')
        context['data'].append({'item': item, 'image_data_base64': image_data_base64})

    context['paginated_data'] = paginated_data  # Add paginated_data to context for pagination links
    return render(request, "home/user_registration.html", context)


def user_register_attendance(request, id):
    uid = int(id)
    current_date = datetime.now().strftime('%Y-%m-%d')
    user_attendance = attendance.objects.filter(emp_id=uid, date_time__contains=current_date)
    context = {'data': []}
    if user_attendance.exists():
        status ="Present"
        for item in user_attendance:
            image_data = item.image 
            image_data_base64 = base64.b64encode(image_data).decode('utf-8')
            context['data'].append({'item': item, 'image_data_base64': image_data_base64, "status":status })
    else:
        user_data=registration.objects.get(id=uid)
        image_data_base64 = base64.b64encode(user_data.image).decode('utf-8')
        context = {'data': []}
        status="Absent"
        context['data'].append({
            "item": user_data, "image_data_base64":image_data_base64, "status":status
        })
    return render(request, "home/user_registration_attendance.html", context)


def get_id(request):
    if request.method == "POST":
        data = json.loads(request.body)
        id = data.get('inputid')
        name = data.get('inputname')
        dept = data.get('inputdepartment')
        dic['id'], dic['name'], dic['dept']=id, name, dept
        if dic['id'] == 'None':
            pass
        else: 
            print(dic['id'])
            print(dic['name'])
            print(dic['dept'])
    return JsonResponse({"status": "success"})


def text_to_speech(text):
    engine = pyttsx3.init()
    engine.say(text)
    engine.runAndWait()
    
    
def speech_thread(text):
    thread = threading.Thread(target=text_to_speech, args=(text,))
    thread.start()
    
    
def capture_video():
    mp_face_detection = mp.solutions.face_detection
    mp_drawing = mp.solutions.drawing_utils
    face_detection = mp_face_detection.FaceDetection(min_detection_confidence=0.5)
    mp_face_mesh = mp.solutions.face_mesh
    face_mesh = mp_face_mesh.FaceMesh()
    # cap = cv2.VideoCapture(0)
    cap = cv2.VideoCapture('/dev/video0')
    # cap = cv2.VideoCapture('/dev/video2')
    # cap = cv2.VideoCapture("rtsp://admin:admin123@10.8.21.48:554/cam/realmonitor?channel=1&subtype=1")
    face_id = dic['id']
    face_position = "Center"
    output_directory = 'emp_dataset/dataset_color/'
    if os.path.isdir(output_directory):
            shutil.rmtree(output_directory)
    if not os.path.isdir(output_directory):
        os.makedirs(output_directory)
    frame1 = None
    image_count = 0
    capture_interval = 3 
    image_counts = {"Left": 0, "Right": 0, "Up": 0, "Down": 0, "Center": 0}
    
    while True:
        ret, frame = cap.read()
        frame = cv2.flip(frame, 1)
        frame2 = frame.copy()
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = face_detection.process(frame_rgb)
        if results.detections:
            for detection in results.detections:
                bbox = detection.location_data.relative_bounding_box
                x, y, w, h = int(bbox.xmin * frame.shape[1]), int(bbox.ymin * frame.shape[0]), \
                            int(bbox.width * frame.shape[1]), int(bbox.height * frame.shape[0])
                x_offset = int(-0.1 * w) 
                y_offset = int(-0.2 * h)  
                x, y, w, h = x + x_offset, y + y_offset, w - 2 * x_offset, h - y_offset
                frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                face_landmarks = face_mesh.process(frame_rgb)
                if face_landmarks.multi_face_landmarks:
                    for face_landmark in face_landmarks.multi_face_landmarks:
                        nose_x = int(face_landmark.landmark[4].x * frame.shape[1])
                        nose_y = int(face_landmark.landmark[4].y * frame.shape[0])
                        if nose_x < x + 0.4 * w:
                            face_position = "Left"
                        elif nose_x > x + 0.6 * w:
                            face_position = "Right"
                        elif nose_y < y + 0.5 * h:
                            face_position = "Up"
                        elif nose_y > y + 0.6 * h:
                            face_position = "Down"
                        else:
                            face_position = "Center"
                        mp_drawing.draw_landmarks(frame, face_landmark, mp_face_mesh.FACEMESH_TESSELATION,
                                                landmark_drawing_spec=None,
                                                connection_drawing_spec=mp_drawing.DrawingSpec(
                                                    color=(255, 255, 255), thickness=1, circle_radius=1))
                else:
                    face_position = "Please show the face properly"
                cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.putText(frame, face_position, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)
        if frame1 is None:
            frame1 = frame.copy()
        if face_position != "Please show the face properly":
            image_counts[face_position] += 1
            if image_counts[face_position] <= 10:
                if frame1 is not None:
                    image_count += 1
                    image_filename = os.path.join(output_directory, f"image_{image_count}.jpg")
                    face_image = frame2[y:y+h, x:x+w]
                    face_image = cv2.resize(face_image, (160, 160))
                    cv2.imwrite(image_filename, frame2)
                    print(f"Saved image: {image_filename}")
                    if image_count==10:
                            img_str = cv2.imencode('.jpeg', frame2)[1].tostring()
                            dic['img_string'] = img_str
                            nparr = np.fromstring(img_str, np.uint8)
                            img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                            cv2.imwrite(f'emp_{face_id}.jpeg', frame2)
                    frame1 = None
                    if image_counts[face_position] == 10:
                        additional_text = f"Captured 10 images for {face_position}"
                        cv2.putText(frame, additional_text, (frame.shape[1] - 200, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9,
                                    (0, 0, 255), 2)
                        speech_thread(additional_text)
                        if image_count == 50:
                            time.sleep(3)
                            text = "all images captured thanks for your patience"
                            speech_thread(text)
                            time.sleep(3)
                            break
            else:
                pass
        ret, frame1 = cv2.imencode('.jpg', frame)
        response_bytes = (b'--frame1\r\n'
                        b'Content-Type: image/jpg\r\n\r\n' + frame1.tobytes() + b'\r\n')
        yield response_bytes
    cap.release()


@gzip.gzip_page
def camera_feed(request):
    try:  
        return StreamingHttpResponse(capture_video(), content_type="multipart/x-mixed-replace;boundary=frame")
    except Exception as e:
        print("An error occurred: ", e)
        return None
    

def train_data(request):
    if request.method == 'POST':

fras/apps/templates/home/page-403.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 403      
              </div>

              <div class="text-center mb-4">
                Access denied - Please authenticate <a href="{% url 'login' %}">Login</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>          
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

fras/apps/templates/home/page-404.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 404      
              </div>

              <div class="text-center mb-4">
                Page not found - <a href="/">Home</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

fras/apps/templates/home/rejected_detection.html
{% extends 'layouts/base.html' %}

{% block title %} Dashboard {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
{% load static %}
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8">
  <title>...</title>
  <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css"> -->
  <link href="{% static 'assets/js/jquery-ui-1.13.2/jquery-ui.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/js/jquery-ui-1.13.2/jquery-ui.structure.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/js/jquery-ui-1.13.2/jquery-ui.theme.min.css' %}" rel="stylesheet">

  <script src="{% static 'assets/js/jquery-3.7.0.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery-ui-1.13.2/jquery-ui.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: 'Poppins', sans-serif;
    }

    .container {
      max-width: 700px;
      width: 100%;
      background-color: #fff;
      padding: 25px 30px;
      border-radius: 5px;
      box-shadow: 0 5px 10px rgba(0, 0, 0, 0.15);
    }

    .container .title {
      font-size: 25px;
      font-weight: 500;
      position: relative;
    }

    .container .title::before {
      content: "";
      position: absolute;
      left: 0;
      bottom: 0;
      height: 3px;
      width: 30px;
      border-radius: 5px;
      background: linear-gradient(135deg, #71b7e6, #9b59b6);
    }

    .content form .user-details {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      margin: 20px 0 12px 0;
    }

    form .user-details .input-box {
      margin-bottom: 15px;
      width: calc(100% / 2 - 20px);
    }

    form .input-box span.details {
      display: block;
      font-weight: 500;
      margin-bottom: 5px;
    }

    .user-details .input-box input {
      height: 45px;
      width: 100%;
      outline: none;
      font-size: 16px;
      border-radius: 5px;
      padding-left: 15px;
      border: 1px solid #ccc;
      border-bottom-width: 2px;
      transition: all 0.3s ease;
    }

    .user-details .input-box input:focus,
    .user-details .input-box input:valid {
      border-color: #9b59b6;
    }

    form .gender-details .gender-title {
      font-size: 20px;
      font-weight: 500;
    }

    form .category {
      display: flex;
      width: 80%;
      margin: 14px 0;
      justify-content: space-between;
    }

    form .category label {
      display: flex;
      align-items: center;
      cursor: pointer;
    }

    form .category label .dot {
      height: 18px;
      width: 18px;
      border-radius: 50%;
      margin-right: 10px;
      background: #d9d9d9;
      border: 5px solid transparent;
      transition: all 0.3s ease;
    }

    #dot-1:checked~.category label .one,
    #dot-2:checked~.category label .two,
    #dot-3:checked~.category label .three {
      background: #9b59b6;
      border-color: #d9d9d9;
    }

    form input[type="radio"] {
      display: none;
    }

    form .button {
      height: 45px;
      margin: 35px 0
    }

    form .button input {
      height: 100%;
      width: 100%;
      border-radius: 5px;
      border: none;
      color: #fff;
      font-size: 18px;
      font-weight: 500;
      letter-spacing: 1px;
      cursor: pointer;
      transition: all 0.3s ease;
      background: linear-gradient(135deg, #71b7e6, #9b59b6);
    }

    form .button input:hover {
      /* transform: scale(0.99); */
      background: linear-gradient(-135deg, #71b7e6, #9b59b6);
    }

    @media(max-width: 584px) {
      .container {
        max-width: 100%;
      }

      form .user-details .input-box {
        margin-bottom: 15px;
        width: 100%;
      }

      form .category {
        width: 100%;
      }

      .content form .user-details {
        max-height: 300px;
        overflow-y: scroll;
      }

      .user-details::-webkit-scrollbar {
        width: 5px;
      }
    }

    @media(max-width: 459px) {
      .container .content .category {
        flex-direction: column;
      }
    }


    table th,
    table td {
      text-align: center;
    }

    table tr:nth-child(even) {
      background-color: #BEF2F5
    }

    .pagination li:hover {
      cursor: pointer;
    }

    .today {
      text-align: center;
    }

    .submit {
      text-align: center;
    }

    #myImg {
      border-radius: 5px;
      cursor: pointer;
      transition: 0.3s;
    }
    
    #myImg:hover {opacity: 0.7;}
    
    /* The Modal (background) */
    .modal {
      display: none; /* Hidden by default */
      position: fixed; /* Stay in place */
      z-index: 1; /* Sit on top */
      padding-top: 100px; /* Location of the box */
      left: 0;
      top: 0;
      width: 100%; /* Full width */
      height: 100%; /* Full height */
      overflow: auto; /* Enable scroll if needed */
      background-color: rgb(0,0,0); /* Fallback color */
      background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
    }
    
    /* Modal Content (Image) */
    .modal-content {
      margin: auto;
      display: block;
      width: 80%;
      max-width: 700px;
    }
    
    /* Caption of Modal Image (Image Text) - Same Width as the Image */
    #caption {
      margin: auto;
      display: block;
      width: 80%;
      max-width: 700px;
      text-align: center;
      color: #ccc;
      padding: 10px 0;
      height: 150px;
    }
    
    /* Add Animation - Zoom in the Modal */
    .modal-content, #caption {
      animation-name: zoom;
      animation-duration: 0.6s;
    }
    
    @keyframes zoom {
      from {transform:scale(0)}
      to {transform:scale(1)}
    }
    
    /* The Close Button */
    .close {
      position: absolute;
      top: 15px;
      right: 35px;
      color: #f1f1f1;
      font-size: 40px;
      font-weight: bold;
      transition: 0.3s;
    }
    
    .close:hover,
    .close:focus {
      color: #bbb;
      text-decoration: none;
      cursor: pointer;
    }
    
    /* 100% Image Width on Smaller Screens */
    @media only screen and (max-width: 700px){
      .modal-content {
        width: 100%;
      }
    }


  </style>

</head>

<body>

  <div class="container" style="margin-top: 30px;">
    <div class="title">Rejected Detections</div>
  </div>
  <div class="container" style="margin-top: 30px;">


    <!-- <form action="" method="post">
      {% csrf_token %}
      {{form.as_p }}
      <input type="submit" class="submit" value="Submit">
    </form> -->



    <table class="table table-striped table-class" id="table-id">
      <thead>

        <tr>
          <th><input type="checkbox" id="select-all"></th>
          <th> unknown </th>
          <th>Status </th>
          <th>Date-Time </th>
          <th>image</th>
          <th>Action</th>
        </tr>

      </thead>

      <tbody>
        {% for item in data %}
        <tr>
          <td><input type="checkbox" class="select-checkbox" data-id="{{ item.item.id }}"></td>

          <td>Anonymous {{item.item.id}}</td>
          <td>{{item.item.status}}</td>
          {% load tz %}
          <td>{{ item.item.date_time|timezone:"Asia/Kolkata"|date:"d-M-Y" }}<br>{{ item.item.date_time|timezone:"Asia/Kolkata"|date:"h:i:s A" }}</td>

          <!-- <td>{{ item.item.date_time|timezone:"Asia/Kolkata"|date:"d-M-Y h:i:s A" }}</td> -->
                    
          <td><img class="myImg" src="data:image/png;base64,{{ item.image_data_base64 }}" alt="Unknown" style="width: 150px; height: 100px;">
              <div class="modal">
                  <span class="close">&times;</span>
                  <img class="modal-content" id="img01">
                  <div class="caption"></div>
              </div>
          </td>
          <td><a href="{% url 'user:delete_rejected' id=item.item.id %}" class="btn btn-danger">Delete</a></td>

          {% comment %} <td>{{ item.image|slice:":18"}}</td> {% endcomment %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <button id="delete-all-btn" class="btn btn-danger">Delete All</button>
    <script>
      $(document).ready(function () {
        // Handle "Delete All" button click
        $('#delete-all-btn').on('click', function () {
            var selectedIds = [];

            // Loop through all checked checkboxes
            $('.select-checkbox:checked').each(function () {
                var itemId = $(this).data('id');
                selectedIds.push(itemId);
            });

            // Check if any checkboxes are selected
            if (selectedIds.length > 0) {
                // Get CSRF token from the cookie
                var csrfToken = document.cookie.match(/csrftoken=([^ ;]+)/)[1];

                // Send an AJAX request to the server to delete selected items
                $.ajax({
                    type: 'POST',
                    url: '{% url "user:delete_selected_rejects" %}',
                    data: { ids: selectedIds, csrfmiddlewaretoken: csrfToken },
                    success: function (data) {
                        // Optionally, update the UI or show a message
                        location.reload(); // Reload the page for simplicity
                    },
                    error: function (error) {
                        console.error('Error deleting items:', error);
                    }
                });
            } else {
                alert('Please select at least one item to delete.');
            }
        });
    });


    $(document).ready(function () {
        // Check/uncheck all checkboxes when the "Select All" checkbox is clicked
        $("#select-all").click(function () {
            $(".select-checkbox").prop("checked", $(this).prop("checked"));
        });

        // Check/uncheck the "Select All" checkbox based on the state of individual checkboxes
        $(".select-checkbox").click(function () {
            if ($(".select-checkbox:checked").length === $(".select-checkbox").length) {
                $("#select-all").prop("checked", true);
            } else {
                $("#select-all").prop("checked", false);
            }
        });
    });
      // Get all modal images
      var modalImages = document.getElementsByClassName("myImg");
  
      // Loop through each modal image and attach click event listener
      for (var i = 0; i < modalImages.length; i++) {
          modalImages[i].onclick = function () {
              var modal = this.nextElementSibling;
              var modalImg = modal.querySelector(".modal-content");
              var captionText = modal.querySelector(".caption");
  
              modal.style.display = "block";
              modalImg.src = this.src;
              captionText.innerHTML = this.alt;
          }
      }
  
      // Get all modal close buttons
      var closeButtons = document.getElementsByClassName("close");
  
      // Loop through each close button and attach click event listener
      for (var j = 0; j < closeButtons.length; j++) {
          closeButtons[j].onclick = function () {
              var modal = this.parentElement;
              modal.style.display = "none";
          }
      }
  </script>
</body>

</html>

{% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>
  function submitFormWithToday() {
    var today = new Date().toISOString().split('T')[0];
    console.log(today[6])
    document.getElementsByName('start_date')[0].value = today;
    document.getElementsByName('end_date')[0].value = today;
    document.forms[0].submit();
  }
</script>
<script>
  function submitFormForWeek() {
    var today = new Date();
    var startOfWeek = new Date(today.setDate(today.getDate() - today.getDay()));
    var endOfWeek = new Date(today.setDate(today.getDate() - today.getDay() + 6));
    var start_date = startOfWeek.toISOString().split('T')[0];
    var end_date = endOfWeek.toISOString().split('T')[0];
    document.getElementsByName('start_date')[0].value = start_date;
    document.getElementsByName('end_date')[0].value = end_date;
    document.forms[0].submit();
  }
</script>
<script>
  function submitFormForMonth() {
    var today = new Date();
    var start_date = new Date(today.getFullYear(), today.getMonth(), 1).toISOString().split('T')[0];
    var end_date = new Date(today.getFullYear(), today.getMonth() + 1, 0).toISOString().split('T')[0];
    document.getElementsByName('start_date')[0].value = start_date;
    document.getElementsByName('end_date')[0].value = end_date;
    document.forms[0].submit();
  }
</script>
<script>
  function submitFormForLastSixMonths() {
    var today = new Date();
    var start_date = new Date(today.getFullYear(), today.getMonth() - 5, 1).toISOString().split('T')[0];
    var end_date = today.toISOString().split('T')[0];
    document.getElementsByName('start_date')[0].value = start_date;
    document.getElementsByName('end_date')[0].value = end_date;
    document.forms[0].submit();
  }
</script>
<script>
  $(document).ready(function () {
    console.log("Calendar is working")
    $(".datetimeinput").datepicker({ changeYear: true, changeMonth: true });
  });
</script>





<script src="/static/assets/vendor/chart.js/dist/Chart.min.js"></script>
<script src="/static/assets/vendor/chart.js/dist/Chart.extension.js"></script>

{% endblock javascripts %}